export const SAVE_INFO = 'SAVE_INFO'
export const SET_INFO = 'SET_INFO'
export const SET_INFO_STATUS ='SET_INFO_STATUS'

export const ADD_PORTFOLIO = 'ADD_PORTFOLIO'
export const SET_PORTFOLIO = 'SET_PORTFOLIO'
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO' 
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO' 
export const SET_PORTFOLIO_STATUS = 'SET_PORTFOLIO_STATUS'

export const ADD_SERVICES ='ADD_SERVICES'
export const SET_SERVICES = 'SET_SERVICES'
export const DELETE_SERVICES ='DELETE_SERVICES'
export const EDIT_SERVICES ='EDIT_SERVICES'
export const SET_SERVICES_STATUS = 'SET_SERVICES_STATUS'

export const ADD_MSG = 'ADD_MSG'
export const SET_MSG = 'SET_MSG'
export const DELETE_MSG = 'DELETE_MSG'
export const SET_MSG_STATUS = 'SET_MSG_STATUS'

export const SET_SOCIAL_LINK ='SET_SOCIAL_LINK'
export const ADD_SOCIAL_LINK ='ADD_SOCIAL_LINK'
export const SET_SOCIAL_LINK_STATUS='SET_SOCIAL_LINK_STATUS'
